spring:
  application:
    name: jdbc
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    initialization-mode: always
mybatis:
  mapper-locations: classpath:com/ssydx/mybatis/dao/*.xml
  type-aliases-package: com.ssydx.mybatis.domain