# Generated by Django 4.2.16 on 2024-11-16 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogcontentmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcommentmodel',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogcomments', to='blog.blogcontentmodel', verbose_name='博文内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogcontentmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogcontents', to='blog.blogauthormodel', verbose_name='博文作者'),
        ),
    ]
