# Generated by Django 4.2.16 on 2024-11-16 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_blogcommentmodel_blog_alter_blogcontentmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcommentmodel',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentnames', to=settings.AUTH_USER_MODEL, verbose_name='评论者姓名'),
        ),
    ]
