# Generated by Django 4.2.16 on 2024-11-16 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_alter_blogcommentmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcommentmodel',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogcomments', to=settings.AUTH_USER_MODEL, verbose_name='评论者姓名'),
        ),
    ]
