# Generated by Django 4.2.16 on 2024-11-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('title', models.CharField(default='遮天', help_text='输入标题', max_length=20, primary_key=True, serialize=False, verbose_name='标题')),
                ('length', models.CharField(choices=[('短篇', (('10000', '一万'), ('50000', '五万'))), ('中篇', (('200000', '二十万'), ('500000', '五十万'))), ('长篇', (('1000000', '一百万'), ('2000000', '两百万'))), ('超长篇', '两百万以上')], max_length=10, verbose_name='长度')),
                ('desc', models.TextField(default='在第一个 JavaScript 板块，带领各位体验编写 JavaScript 程序前，首先回答一些基本问题：「什么是 JavaScript？」，「它看上去是什么样的？」，「它能做什么？」。此后，我们将详细讨论一些关键构件，例如变量、字符串、数值和数组。', verbose_name='描述')),
                ('content', models.TextField(default='在第一个 JavaScript 板块，带领各位体验编写 JavaScript 程序前，首先回答一些基本问题：「什么是 JavaScript？」，「它看上去是什么样的？」，「它能做什么？」。此后，我们将详细讨论一些关键构件，例如变量、字符串、数值和数组。')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品列表',
            },
        ),
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='输入姓名', max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1, verbose_name='性别')),
                ('age', models.IntegerField(default=20, verbose_name='年龄')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者列表',
                'ordering': ['-gender', 'name'],
                'permissions': [('new perm', '新权限')],
                'default_permissions': ('add', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(default='玄幻', help_text='输入类型', max_length=10, unique=True, verbose_name='类型')),
            ],
            options={
                'verbose_name': '类型',
                'verbose_name_plural': '类型列表',
            },
        ),
        migrations.AddConstraint(
            model_name='authormodel',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 18), ('age__lte', 65)), name='年龄不得小于18或大于65', violation_error_message='违反约束：“%(name)s”'),
        ),
        migrations.AddConstraint(
            model_name='authormodel',
            constraint=models.UniqueConstraint(fields=('name', 'gender'), name='姓名性别唯一'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='novel.authormodel'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='genre',
            field=models.ManyToManyField(related_name='articles', to='novel.genremodel'),
        ),
    ]
