spring:
  datasource:
    url: jdbc:mysql://localhost:3306/website
    username: ssydx
    password: 
  redis:
    host: 172.29.68.48
    port: 6379
    database: 1
      
logging.level.org.springframework.security: DEBUG
spring.aop.proxy-target-class: true

server:
  port: 8099
