spring:
  datasource:
    url: jdbc:mysql://localhost:3306/website
    username: ssydx
    password: 
  sql:
    init:
      mode: always
mybatis:
  mapper-locations: classpath:com/ssydx/website/app/dao/*.xml
