# Generated by Django 4.2.16 on 2024-11-17 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='作者姓名', help_text='输入作者的姓名', max_length=10, unique=True, verbose_name='作者姓名')),
                ('age', models.IntegerField(db_column='作者年龄', verbose_name='作者年龄')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], db_column='作者性别', max_length=1, verbose_name='作者性别')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, db_column='创建时间', verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, db_column='修改时间', verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '作者信息',
                'verbose_name_plural': '作者列表',
                'db_table': '作者信息表',
                'ordering': ['gender', '-age'],
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='书籍名称', default='西游记', help_text='输入一个书籍标题', max_length=50, unique=True, verbose_name='书籍名称')),
                ('desc', models.TextField(db_column='书籍简介', help_text='输入简短描述', verbose_name='书籍简介')),
                ('chrcount', models.DecimalField(db_column='书籍字数(万)', decimal_places=2, default=123.32, help_text='书籍字数，单位为万', max_digits=6, verbose_name='书籍字数(万)')),
                ('author', models.ForeignKey(db_column='作者姓名', on_delete=django.db.models.deletion.CASCADE, related_name='书籍集合', to='catalog.authormodel', to_field='name')),
            ],
            options={
                'verbose_name': '书籍信息',
                'verbose_name_plural': '书籍列表',
                'db_table': '书籍信息表',
                'ordering': ['?'],
                'permissions': [('can_delete_book', '删除书籍'), ('can_update_book', '更新书籍'), ('can_add_book', '增加书籍')],
            },
        ),
        migrations.AddConstraint(
            model_name='authormodel',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 18), ('age__lte', 60)), name='年龄约束'),
        ),
        migrations.AddIndex(
            model_name='bookmodel',
            index=models.Index(fields=['title', 'author'], name='联合索引'),
        ),
    ]
