# Generated by Django 4.2.16 on 2024-11-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookmodel',
            index=models.Index(fields=['author'], name='作者索引'),
        ),
    ]
