# Generated by Django 4.2.16 on 2024-11-07 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_tb1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='教室名', max_length=10)),
                ('size', models.IntegerField(help_text='教室大小', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='stu_tb1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='学生姓名', max_length=10)),
                ('age', models.IntegerField(help_text='学生年龄')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], help_text='性别', max_length=1)),
                ('desciption', models.TextField(blank=True, default='这是一段个人描述', help_text='个人描述', null=True)),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stu_by_class_name', to='field.class_tb1')),
            ],
        ),
    ]
