# Generated by Django 4.2.16 on 2024-11-07 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_class_tb1_stu_tb1'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_tb1',
            name='class_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stu_by_class_size', to='field.class_tb1', to_field='size'),
            preserve_default=False,
        ),
    ]
