# Generated by Django 4.2.16 on 2024-11-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0003_stu_tb1_class_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu_tb1',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='stu_tb1',
            name='class_size',
        ),
        migrations.DeleteModel(
            name='class_tb1',
        ),
        migrations.DeleteModel(
            name='stu_tb1',
        ),
    ]
