# Generated by Django 4.2.16 on 2024-11-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0004_remove_stu_tb1_class_name_remove_stu_tb1_class_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='prod',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
            ],
        ),
    ]
