# Generated by Django 4.2.16 on 2024-11-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0005_prod'),
    ]

    operations = [
        migrations.CreateModel(
            name='prod1',
            fields=[
                ('myid', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
