# Generated by Django 4.2.16 on 2024-11-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0006_prod1'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod1',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
