# Generated by Django 4.2.16 on 2024-11-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0007_prod1_price1'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod1',
            name='dedate',
            field=models.DateField(default='2024-10-01'),
        ),
        migrations.AddField(
            model_name='prod1',
            name='detime',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
