# Generated by Django 4.2.16 on 2024-11-07 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0008_prod1_dedate_prod1_detime'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod1',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prod1',
            name='modifytime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
