# Generated by Django 4.2.16 on 2024-11-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0009_prod1_createtime_prod1_modifytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod1',
            name='datetime',
            field=models.DateTimeField(default='2023-12-10 12:01:01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prod1',
            name='price2',
            field=models.FloatField(default=20.0001),
        ),
    ]
