# Generated by Django 4.2.16 on 2024-11-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0010_prod1_datetime_prod1_price2'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod1',
            name='desc',
            field=models.TextField(default='一段介绍'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prod1',
            name='name',
            field=models.CharField(default='名称', max_length=20),
            preserve_default=False,
        ),
    ]
