# Generated by Django 4.2.16 on 2024-11-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0011_prod1_desc_prod1_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod1',
            name='bool',
            field=models.BooleanField(default=True),
        ),
    ]
