# Generated by Django 4.2.16 on 2024-11-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0012_prod1_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod1',
            name='positiveprice',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
