# Generated by Django 4.2.16 on 2024-11-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0013_prod1_positiveprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod1',
            name='email',
            field=models.EmailField(default='ssydx@qq.com', max_length=254),
        ),
        migrations.AddField(
            model_name='prod1',
            name='url',
            field=models.URLField(default='www.baidu.com'),
        ),
    ]
