# Generated by Django 4.2.16 on 2024-11-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0014_prod1_email_prod1_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod1',
            name='file1',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
