# Generated by Django 4.2.16 on 2024-11-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0015_prod1_file1'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod1',
            name='content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
