# Generated by Django 4.2.16 on 2024-11-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0016_prod1_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod1',
            name='content',
        ),
    ]
