# Generated by Django 4.2.16 on 2024-11-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0017_remove_prod1_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod1',
            name='image1',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
