# Generated by Django 4.2.16 on 2024-11-07 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0018_prod1_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod1',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
