# Generated by Django 4.2.16 on 2024-11-07 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0020_alter_prod1_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod1',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
