# Generated by Django 4.2.16 on 2024-11-07 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0021_alter_prod1_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod1',
            name='uid1',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
