# Generated by Django 4.2.16 on 2024-11-07 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0022_prod1_uid1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod1',
            name='uid1',
            field=models.CharField(default=uuid.uuid4, help_text='唯一标识', max_length=50, verbose_name='易读名称'),
        ),
    ]
