# Generated by Django 4.2.16 on 2024-11-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0023_alter_prod1_uid1'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod1',
            name='choice',
            field=models.CharField(choices=[('1', '一'), ('2', '二'), ('3', '三')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
