# Generated by Django 4.2.16 on 2024-11-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0024_prod1_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod1',
            name='choice',
            field=models.CharField(choices=[(None, ''), ('1', '一'), ('2', '二'), ('3', '三')], max_length=1),
        ),
    ]
