# Generated by Django 4.2.16 on 2024-11-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0026_alter_prod1_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='M1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('create_datetime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('home_group', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
