# Generated by Django 4.2.16 on 2024-11-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0027_m1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m1',
            options={'ordering': ['name'], 'verbose_name': '%(app_label)s_%(class)s_detail', 'verbose_name_plural': '%(app_label)s_%(class)s_list'},
        ),
    ]
