# Generated by Django 4.2.16 on 2024-11-27 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0028_alter_m1_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InhreritModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='m1',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='I1',
            fields=[
                ('inhreritmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='field.inhreritmodel')),
                ('home_group', models.CharField(max_length=5)),
            ],
            bases=('field.inhreritmodel',),
        ),
    ]
