spring:
  application:
    name: datajpa
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  jpa:
    database: h2
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: ''