const tb = document.getElementById('tb1');
const span = document.querySelector("#zjsl");
console.log(tb.contains(span));
console.log(tb.hasChildNodes());
document.body.appendChild(document.querySelector('#searchbox1'));
document.body.appendChild(document.querySelector('h1').cloneNode(true));
document.body.lastElementChild.remove();
document.forms[0].removeChild(document.forms[0].firstElementChild);
document.querySelector('caption').replaceChild(document.createTextNode('购物车列表'),document.querySelector('caption').childNodes[0]);
console.log(tb.hasAttribute('class'));
console.log(tb.hasAttributes());
console.log(tb.getAttribute('class'));
console.log(tb.getAttributeNode('class'));
console.log(tb.getAttributeNode('class'));
tb.setAttribute('class','tc1 tc2');
console.log(tb.getAttributeNode('class'));
const attr = document.createAttribute('class');
attr.value = 'tc10 tc20';
tb.setAttributeNode(attr);
console.log(tb.getAttributeNode('class'));
console.log(tb.removeAttribute('title'));
console.log(tb.removeAttributeNode(tb.getAttributeNode('class')));
console.log(tb.children[1].compareDocumentPosition(tb.children[0]));
console.log(tb.children[0].compareDocumentPosition(tb.children[1]));
console.log(tb.compareDocumentPosition(tb.firstElementChild));
console.log(tb.lastElementChild.compareDocumentPosition(tb));
document.forms[0].insertAdjacentElement('beforebegin',document.createElement('input'));
document.forms[0].insertAdjacentHTML('afterbegin','<input type="checkbox" checked><br/>');
document.forms[0].insertAdjacentText('afterend','<input type="checkbox" checked> <br/>');
document.forms[0].insertBefore(document.createComment('插入注释'),null);
console.log(document.querySelectorAll('span')[4].isEqualNode(document.querySelectorAll('span')[5]));
console.log(document.querySelectorAll('span')[5].isSameNode(document.querySelectorAll('span')[5]));
console.log(tb.matches('[accesskey="k"]'));
document.querySelectorAll('span')[5].appendChild(document.createTextNode('文本1  '));
document.querySelectorAll('span')[5].appendChild(document.createTextNode('文本2'));
console.log(document.querySelectorAll('span')[5].childNodes.length);
console.log(document.querySelectorAll('span')[5].normalize());
// document.querySelector('img').focus(); // 由于开启会造成焦点变换到预览界面，因此关闭
console.log(document.activeElement);
document.querySelector('img').blur();
console.log(document.activeElement);
console.log(document.getElementById('kltaishaola').closest('[lang="zh-CN"]'));
document.forms[0].children[0].click();