const tb = document.querySelector('table');
console.log(tb);
console.log(tb.childNodes);
console.log(tb.childNodes[0].nodeType);
console.log(tb.childNodes[1].nodeType);
console.log(tb.childNodes[3].nodeType);
console.log(tb.childNodes[0].nodeName);
console.log(tb.childNodes[1].nodeName);
console.log(tb.childNodes[3].nodeName);
console.log(tb.childNodes[0].nodeValue);
console.log(tb.childNodes[1].nodeValue);
console.log(tb.childNodes[3].nodeValue);
const attrs = tb.attributes;
console.log(attrs);
console.log(attrs[0].nodeType);
console.log(attrs[0].nodeName);
console.log(attrs[0].nodeValue);
console.log(document.nodeType);
console.log(document.nodeName);
console.log(document.nodeValue);