# Generated by Django 4.2.16 on 2024-11-24 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(db_column='类别', db_comment='输入文章类别', default='HTML', help_text='请输入文章类别', max_length=20, unique=True, verbose_name='类别')),
            ],
            options={
                'verbose_name': '类型',
                'verbose_name_plural': '类型列表',
                'db_table': '类型表',
                'db_table_comment': '类型信息表',
            },
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='genre',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aritcles', to='blog.genremodel'),
        ),
    ]
