# Generated by Django 4.2.16 on 2024-11-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_articlemodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='genremodel',
            name='content',
            field=models.TextField(db_column='类别文档', db_comment='输入文章类别文档', default='层叠样式表——或 CSS——是你在学完 HTML 之后应该学习的第一门技术。HTML 用于为你的内容定义结构和语义，CSS 用于为内容提供样式和对内容进行布局。例如，你可以使用 CSS 更改内容的字体、颜色、大小和间距，将内容分成多列，或添加动画和其它装饰特性。', help_text='请输入类别文档', verbose_name='类别文档'),
        ),
        migrations.AddField(
            model_name='genremodel',
            name='desc',
            field=models.CharField(db_column='类别描述', db_comment='输入文章类别描述', default='层叠样式表——或 CSS——是你在学完 HTML 之后应该学习的第一门技术。HTML 用于为你的内容定义结构和语义，CSS 用于为内容提供样式和对内容进行布局。例如，你可以使用 CSS 更改内容的字体、颜色、大小和间距，将内容分成多列，或添加动画和其它装饰特性。', help_text='请输入类别描述', max_length=200, verbose_name='类别描述'),
        ),
    ]
