# Generated by Django 4.2.16 on 2024-11-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_genremodel_content_genremodel_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='genremodel',
            old_name='genre',
            new_name='name',
        ),
    ]
