# Generated by Django 4.2.16 on 2024-11-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('male', '男性'), ('female', '女性')], default='male', max_length=10),
        ),
    ]
