/*
 * This file is generated by jOOQ.
 */
package com.ssydx.jooq.domain;


import com.ssydx.jooq.domain.tables.UserInfo;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Javadb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>javadb</code>
     */
    public static final Javadb JAVADB = new Javadb();

    /**
     * The table <code>javadb.user_info</code>.
     */
    public final UserInfo USER_INFO = UserInfo.USER_INFO;

    /**
     * No further instances allowed
     */
    private Javadb() {
        super("javadb", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            UserInfo.USER_INFO
        );
    }
}
