/*
 * This file is generated by jOOQ.
 */
package com.ssydx.jooq.domain;


import com.ssydx.jooq.domain.tables.UserInfo;
import com.ssydx.jooq.domain.tables.records.UserInfoRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * javadb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UserInfoRecord> KEY_USER_INFO_PRIMARY = Internal.createUniqueKey(UserInfo.USER_INFO, DSL.name("KEY_user_info_PRIMARY"), new TableField[] { UserInfo.USER_INFO.ID }, true);
}
