/*
 * This file is generated by jOOQ.
 */
package com.ssydx.jooq.domain;


import com.ssydx.jooq.domain.tables.UserInfo;


/**
 * Convenience access to all tables in javadb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>javadb.user_info</code>.
     */
    public static final UserInfo USER_INFO = UserInfo.USER_INFO;
}
